### ISSUE TITLE
could you please upload the file of lfw_feats_sphereface6_iter_50000.mat

### ISSUE THREAD

**Issue by honghuCode** [goodluckcwl/Face-Verification#2]
could you please upload the file of lfw_feats_sphereface6_iter_50000.mat,and tell me the methods of getting the roc curve?thank you.

**Comment by goodluckcwl** [comment]
You can get the roc curve easily. Please refer to https://en.wikipedia.org/wiki/Receiver_operating_characteristic.
Features of LFW can be extracted by matlab interface of Caffe.
